#!/bin/sh

# This script will compile or run another finishing operation on a document. I
# have this script run via vim.
#
# tex files: Compiles to pdf, including bibliography if necessary
# md files: Compiles to pdf via pandoc
# rmd files: Compiles via R Markdown
# c files: Compiles via whatever compiler is set to cc. Usually gcc.
# py files: runs via python command
# go files: compiles and runs with "go run"
# config.h files: (For suckless utils) recompiles and installs program.
# all others: run `sent` to show a presentation

file=$(stat -f "$1")
dir=$(dirname "$file")
base="${file%.*}"
shebang=$(sed -n 1p "$file")

cd "$dir" || exit

textype() { \
	command="pdflatex"
	#( sed 5q "$file" | grep -i -q 'xelatex' ) && command="xelatex"
	#( sed 5q "$file" | grep -i -q 'minted' ) && command="pdflatex -shell-escape"
	( sed 5q "$file" | grep -i -q 'draftmode' ) && command="pdflatex -draftmode" && $command --output-directory="$dir" "$base" && return
	$command --output-directory="$dir" "$base" &&
	grep -i bibliographystyle "$file" >/dev/null &&
	bibtex "$base" &&
	$command --output-directory="$dir" "$base" &&
	$command --output-directory="$dir" "$base"
	}

shebangtest() {
	case "$shebang" in
		\#\!*) "$file" ;;
		*) sent "$file" 2>/dev/null & ;;
	esac
}

case "$file" in
	*\.tex) textype "$file" ;;
	*\.md) pandoc "$file" -o "$base".pdf ;;
	*config.h) make && sudo make install ;;
    *\.c) cc "$file" -o "$base" && "$base" ;;
	*\.py) python "$file" ;;
	*\.tikz) tikz2png "$file" ;;
	*) shebangtest ;;
esac
