#!/bin/sh

# runs in vim on current file.
#
# .tex files: Compiles to pdf, including bibliography if necessary
# .md files: Compiles to pdf via pandoc
# config.h files: Recompiles and installs program.
# .c files: Compiles via whatever compiler is set to cc. And runs.
# .py files: runs via python command
# otherwise checks if it begins with "#!" then runs it

file=$(stat -f "$1")
dir=$(dirname "$file")
base="${file%.*}"

cd "$dir" || exit

case "$file" in
	*\.tex) latexmk -pdf $file && latexmk -c ;;
	*\.md) pandoc "$file" -o "$base".pdf ;;
	*config.h) make && sudo make install ;;
    *\.c) cc "$file" -o "$base" && "$base" ;;
	*\.py) python "$file" ;;
	*\.tikz) tikz2png "$file" ;;
	*) [ "$(sed -n 1p compiler | colrm 3)" = '#!' ] && "$file" || echo "Nothing Interesting Happened" ;; # Tests for shebang
esac
